export enum Channel {
  SHORTCUT = 'SHORTCUT',
  UPDATE_AVAILABLE = 'UPDATE_AVAILABLE',
}

export enum Action {
  DELETE = 'DELETE',
  SETTINGS = 'SETTINGS',
  NEW = 'NEW',
  EDIT = 'EDIT',
  COMPLETE = 'COMPLETE',
  CLEAR = 'CLEAR',
  RESET = 'RESET',
  FIRST = 'FIRST',
  SECOND = 'SECOND',
  THIRD = 'THIRD',
  FOURTH = 'FOURTH',
  FIFTH = 'FIFTH',
  SIXTH = 'SIXTH',
  SEVENTH = 'SEVENTH',
  EIGHTH = 'EIGHTH',
  LAST = 'LAST',
}
